// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.NpgSql
{
    public partial class Cclistapreciosconcepto
    {
        public string Lpdivisionid { get; set; }
        public short Lpconceptocon { get; set; }
        public string Lpconceptoid { get; set; }
        public string Lpconceptodes { get; set; }
        public decimal Lpconceptoprecio { get; set; }
        public string Lpconceptogeneracion { get; set; }
        public string Companiaid { get; set; }
        public DateTime Lpconceptofecini { get; set; }
        public DateTime Lpconceptofecfin { get; set; }
        public string Fecvenid { get; set; }
        public char? Lpconceptogrupo { get; set; }
        public string Varianteid { get; set; }
    }
}