// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.NpgSql
{
    public partial class Etlalumno
    {
        public int? Crmid { get; set; }
        public string Crmnombre { get; set; }
        public string Crmapaterno { get; set; }
        public string Crmamaterno { get; set; }
        public DateTime? Crmfenac { get; set; }
        public char? Crmsexo { get; set; }
        public DateTime? Crmmodfecha { get; set; }
        public long? Crmmunicipio { get; set; }
        public DateTime? Crmregfecha { get; set; }
        public string Alunocontrol { get; set; }
        public string Coddescripcion { get; set; }
        public short? Alureganio { get; set; }
        public string Cicloatual { get; set; }
        public string Alumodalidad { get; set; }
        public short? Aluregperiodo { get; set; }
        public string Aluestado { get; set; }
        public string Aacfmail { get; set; }
        public short? Aacsemestreactual { get; set; }
        public string Aacfnomtutor { get; set; }
        public string Aacfapellidop { get; set; }
        public string Aacfapellidom { get; set; }
        public string Aacftelefonot { get; set; }
        public string Aacftelefono { get; set; }
        public string Acarid { get; set; }
        public string Crmclave { get; set; }
        public string Bcid { get; set; }
        public decimal? Beparcialidades { get; set; }
        public int? Beid { get; set; }
    }
}