// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.NpgSql
{
    public partial class Etlcatalogoconcepto
    {
        public string Cptipodoc { get; set; }
        public string Cpconcepto { get; set; }
    }
}