// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.NpgSql
{
    public partial class Etlcuentasdetalle
    {
        public long? Cpid { get; set; }
        public long? Cpnodoc { get; set; }
        public string Cpconcepto { get; set; }
        public string Cpdoclinea { get; set; }
        public decimal? Cpimportetotal { get; set; }
        public decimal? Cpimportepend { get; set; }
        public DateTime? Cpfechaven { get; set; }
        public DateTime? Cpfecreg { get; set; }
        public decimal? Aluid { get; set; }
        public short? Cpestatus { get; set; }
        public long? Cpidref { get; set; }
    }
}