// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.NpgSql
{
    public partial class Etlpago
    {
        public long? Pagoid { get; set; }
        public decimal? Aluid { get; set; }
        public string Pagocbid { get; set; }
        public string Pagotipodoc { get; set; }
        public string Pagometodoid { get; set; }
        public decimal? Pagoimportepend { get; set; }
        public decimal? Pagoimportetotal { get; set; }
        public string Pagoreferencia { get; set; }
        public string Pagorefbancaria { get; set; }
        public string Pagona { get; set; }
        public DateTime? Pagofechacreacion { get; set; }
        public DateTime? Pagofechacontable { get; set; }
        public DateTime? Pagofechabancaria { get; set; }
        public string Pagoadicional { get; set; }
    }
}