// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.NpgSql
{
    public partial class Etlreferencia
    {
        public string Referenciaid { get; set; }
        public decimal? Aluid { get; set; }
        public DateTime? Reffecreg { get; set; }
        public DateTime? Referenciafechaini { get; set; }
        public DateTime? Referenciafechavig { get; set; }
        public decimal? Referenciatotal { get; set; }
        public string Referenciaestatus { get; set; }
    }
}