// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.NpgSql
{
    public partial class Etlreferenciasconceptos
    {
        public string Referenciaid { get; set; }
        public long? Cpid { get; set; }
        public decimal? Refmonto { get; set; }
    }
}