// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.NpgSql
{
    public partial class Taalumnoconexion
    {
        public long Aluid { get; set; }
        public int Aacfid { get; set; }
        public byte[] Aacfoto { get; set; }
        public string AacfotoGxi { get; set; }
        public string Aacfcurp { get; set; }
        public string Aacftelefono { get; set; }
        public string Aacfmail { get; set; }
        public string Aacfnomtutor { get; set; }
        public string Aacfapellidop { get; set; }
        public string Aacfapellidom { get; set; }
        public string Aacfcolonia { get; set; }
        public string Aacfcallenum { get; set; }
        public string Aacfmunicipio { get; set; }
        public string Aacfestado { get; set; }
        public string Aacftelefonot { get; set; }
        public string Aacfmailt { get; set; }
        public string Aacfalergias { get; set; }
        public string Aacftiposangre { get; set; }
        public string Aacfpadecimientos { get; set; }
        public string Aacfcomentarios { get; set; }
        public string Aacfsecundaria { get; set; }
        public string Aacfseclugar { get; set; }
        public string Aacfsecedo { get; set; }
        public string Aacfbachiller { get; set; }
        public string Aacfbachlugar { get; set; }
        public string Aacfbachedo { get; set; }
        public short? Aacsemestreactual { get; set; }
        public string Aacfparentescocont { get; set; }
        public string Aacftelefonocont { get; set; }
        public string Aacfedocont { get; set; }
        public string Aacfamunicipiocont { get; set; }
        public string Aacfcallenumcont { get; set; }
        public string Aacfcoloniacont { get; set; }
        public string Aacfamaternocont { get; set; }
        public string Aacfapaternocont { get; set; }
        public string Aacfnombrecont { get; set; }
        public string Aacfunirev { get; set; }
        public string Acarid { get; set; }
        public string Aacfnia { get; set; }
        public char? Aacsemestregrupo { get; set; }
        public string Aacffb { get; set; }
        public string Aacfreligion { get; set; }
        public string Aacfresidente { get; set; }
        public string Aacforiginario { get; set; }
        public long? Aacfcedula { get; set; }
        public string Aacftipotitulacion { get; set; }
        public DateTime? Aacffechatitulacion { get; set; }
        public DateTime? Aacfhoratitulacion { get; set; }
        public string Aacfnolibro { get; set; }
        public string Aacffoja { get; set; }
        public string Aacfnolibroo { get; set; }
        public string Aacffojao { get; set; }
        public short? Aacfegreanio { get; set; }
        public short? Aacfegreperiodo { get; set; }
        public short? Aacftituladoanio { get; set; }
        public short? Aacftituladoperiodo { get; set; }
        public string Aacfbachpais { get; set; }
        public string Aacfextranjero { get; set; }
        public short? Aacfegresado { get; set; }
        public short? Aacftitulado { get; set; }
        public string Aacfcertificado { get; set; }
        public char? Aacgrupo { get; set; }
        public string Aacftitulotesis { get; set; }
        public string Aacftelefonoc { get; set; }
        public string Aacffacebook { get; set; }
        public string Aacftwitter { get; set; }
        public short? Aacfsuspendido { get; set; }
        public short? Aacfacusado { get; set; }
        public string Aacfseguro { get; set; }
        public decimal? Aacfbachprom { get; set; }
        public DateTime? Aacfbachcert { get; set; }
        public DateTime? Aacfbachinicio { get; set; }
        public DateTime? Aacfbachfin { get; set; }
        public short? Aacfgradoest { get; set; }
        public short? Aacfequimat { get; set; }
        public string Aacfnacionalidad { get; set; }
        public short? Aacmodalidad { get; set; }
        public DateTime? Aacffechanact { get; set; }
    }
}