// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.NpgSql
{
    public partial class Talumnoestatus
    {
        public long Alueid { get; set; }
        public long? Aluestid { get; set; }
        public long? Aluid { get; set; }
        public DateTime? Aluestfecha { get; set; }
        public DateTime? Aluesthora { get; set; }
        public short? Aluestanio { get; set; }
        public short? Aluestperiodo { get; set; }
        public long? Usuid { get; set; }
        public string Aluestcomentario { get; set; }

        public virtual Talumno Alu { get; set; }
    }
}