// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.NpgSql
{
    public partial class Talumno
    {
        public Talumno()
        {
            Talumnoestatus = new HashSet<Talumnoestatus>();
        }

        public long Aluid { get; set; }
        public long? Alucompany { get; set; }
        public string Alunocontrol { get; set; }
        public char? Alunoverifica { get; set; }
        public string Alunoant { get; set; }
        public char? Alunovant { get; set; }
        public string Alunopro { get; set; }
        public char? Alunovpro { get; set; }
        public string Aluescprocedencia { get; set; }
        public string Aluintereses { get; set; }
        public string Alumunicipio2 { get; set; }
        public long? Aluestatusid { get; set; }
        public string Tpaident { get; set; }
        public long? Covid { get; set; }
        public int? Alugeneracta { get; set; }
        public decimal? Aluimporte { get; set; }
        public string Aluinspago { get; set; }
        public short? Aluadeudo { get; set; }
        public short? Aluretenfac { get; set; }
        public decimal? Alucredlim { get; set; }
        public string Alucredmsg { get; set; }
        public string Alucredopen { get; set; }
        public string Alucredreview { get; set; }
        public DateTime? Alucredfopen { get; set; }
        public DateTime? Alucredfreview { get; set; }
        public DateTime? Alucredfnreview { get; set; }
        public string Alucredmsgtmp { get; set; }
        public string Alucbrpolitica { get; set; }
        public char? Alucbrenviocta { get; set; }
        public short? Alucbrreporte { get; set; }
        public short? Alucbrpedo { get; set; }
        public short? Alucbrmorozidad { get; set; }
        public short? Alucbravisosmor { get; set; }
        public long? Aluactivo { get; set; }
        public long? Aluregusuario { get; set; }
        public DateTime? Aluregfecha { get; set; }
        public string Alureghora { get; set; }
        public string Aluregprog { get; set; }
        public long? Alumodusuario { get; set; }
        public DateTime? Alumodfecha { get; set; }
        public string Alumodhora { get; set; }
        public string Alumodprog { get; set; }
        public short? Alufac { get; set; }
        public string Alufacrfc { get; set; }
        public string Alufacrazons { get; set; }
        public string Alufacdir { get; set; }
        public string Alufacemail { get; set; }
        public string Alugeneracion { get; set; }
        public string Aludivision { get; set; }
        public short? Alureganio { get; set; }
        public short? Aluregperiodo { get; set; }
        /// <summary>
        /// Estatus AcadÃÂ©mico para Kardex
        /// 
        /// ***  1 Regular
        /// ***  2 Irregular
        /// </summary>
        public short? Aluestatusacademico { get; set; }
        public string Alumodalidad { get; set; }
        public string Aluestado { get; set; }
        public string Alucp { get; set; }
        public string Aluciudadnac { get; set; }
        public short? Alufactipo { get; set; }
        public decimal? Alufacverificacion { get; set; }
        public DateTime? Alufacfechareg { get; set; }
        public DateTime? Alufachorareg { get; set; }
        public DateTime? Alufacsolicitud { get; set; }
        public decimal? Alufacusuid { get; set; }
        public char? Alusexot { get; set; }
        public string Aluocupaciont { get; set; }
        public decimal? Aluingresot { get; set; }
        public string Aluresidencia { get; set; }
        public string Alulocalidad { get; set; }

        public virtual ICollection<Talumnoestatus> Talumnoestatus { get; set; }
    }
}