// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.NpgSql
{
    public partial class Tcarrera
    {
        public int Carid { get; set; }
        public string Carclave { get; set; }
        public string Carnombre { get; set; }
        public long Areid { get; set; }
    }
}