// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.NpgSql
{
    public partial class Tcodigo
    {
        public int Codid { get; set; }
        public string Codmodulo { get; set; }
        public string Codgeneral { get; set; }
        public string Codespecifico { get; set; }
        public string Coddescripcion { get; set; }
        public long? Codreferencia { get; set; }
        public long Codactivo { get; set; }
        public short? Codnivel { get; set; }
        public string Coddep { get; set; }
    }
}