// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.NpgSql
{
    public partial class Tcrm
    {
        public int Crmid { get; set; }
        public string Crmclave { get; set; }
        public string Crmnombre { get; set; }
        public string Crmapaterno { get; set; }
        public string Crmamaterno { get; set; }
        public DateTime? Crmfenac { get; set; }
        public long? Crmedad { get; set; }
        public char? Crmsexo { get; set; }
        public char? Crmedocivil { get; set; }
        public long? Crmpaisid { get; set; }
        public string Crmnacionalidad { get; set; }
        public long? Crmedo { get; set; }
        public long? Crmmunicipio { get; set; }
        public string Crmdireccion { get; set; }
        public string Crmcp { get; set; }
        public string Crmcomentarios { get; set; }
        public long? Crmcompany { get; set; }
        public long? Crmactivo { get; set; }
        public string Crmmotivo { get; set; }
        public byte[] Crmimagen { get; set; }
        public string CrmimagenGxi { get; set; }
        public string Crmcat01 { get; set; }
        public string Crmcat02 { get; set; }
        public string Crmcat03 { get; set; }
        public string Crmcat04 { get; set; }
        public string Crmcat05 { get; set; }
        public string Crmcat06 { get; set; }
        public string Crmcat07 { get; set; }
        public string Crmcat08 { get; set; }
        public string Crmcat09 { get; set; }
        public string Crmcat10 { get; set; }
        public string Crmmoneda { get; set; }
        public long? Crmmanagercrd { get; set; }
        public long? Crmmanagercrb { get; set; }
        public long? Crmregusuario { get; set; }
        public DateTime? Crmregfecha { get; set; }
        public string Crmreghora { get; set; }
        public string Crmregprog { get; set; }
        public long? Crmmodusuario { get; set; }
        public DateTime? Crmmodfecha { get; set; }
        public string Crmmodhora { get; set; }
        public string Crmmodprog { get; set; }
    }
}