// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class ActivoPara
    {
        public int ApCuentaId { get; set; }
        public int? ApEmpresa { get; set; }

        public virtual CuentaBancaria ApCuenta { get; set; }
        public virtual Empresas ApEmpresaNavigation { get; set; }
    }
}