// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class Alergias
    {
        public int AAlergiaId { get; set; }
        public string AAlergia { get; set; }
        public string ADescripcion { get; set; }
    }
}