// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class Becas
    {
        public int BecasId { get; set; }
        public string BecasClave { get; set; }
        public string BecasNombre { get; set; }
        public string BecasDescripcion { get; set; }
        public bool BecasActiva { get; set; }
        public long Usuid { get; set; }
        public string BecasResponsable { get; set; }
        public int? CategoriaId { get; set; }
        public int? ConId { get; set; }
        public bool BecasProm { get; set; }
    }
}