// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class Campanameta
    {
        public int Campid { get; set; }
        public long? Usuid { get; set; }
        public int Cmid { get; set; }
        public int? Cmmeta { get; set; }
        public DateTime Cmfecini { get; set; }
        public DateTime Cmfecfin { get; set; }

        public virtual Campana Camp { get; set; }
        public virtual Usuario Usu { get; set; }
    }
}