// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class CatalogoConvenios
    {
        public CatalogoConvenios()
        {
            Convenios = new HashSet<Convenios>();
        }

        public int CconvId { get; set; }
        public string CconvDescripcion { get; set; }
        public long CconvUsuid { get; set; }
        public DateTime CconvFechaRegistro { get; set; }

        public virtual ICollection<Convenios> Convenios { get; set; }
    }
}