// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class CatalogoSaltoPago
    {
        public int CsalId { get; set; }
        public string CsalDescripcion { get; set; }
        public long CsalUsuid { get; set; }
        public DateTime CsalFechaRegistro { get; set; }
    }
}