// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class Categoriabeca
    {
        public Categoriabeca()
        {
            Becas = new HashSet<Becas>();
        }

        public int CategoriaId { get; set; }
        public string DescripcionCat { get; set; }
        public string ClaveCat { get; set; }

        public virtual ICollection<Becas> Becas { get; set; }
    }
}