// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class ConfiguracionPagos
    {
        public int ConfId { get; set; }
        public int? ConfAño { get; set; }
        public int? ConfPeriodo { get; set; }
        public int? ConfRecargos { get; set; }
        public int? ConfDiaVencimiento { get; set; }
    }
}