// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class CuentaBancaria
    {
        public int CbCuentaId { get; set; }
        public int CbBancoId { get; set; }
        public string CbCuenta { get; set; }
        public string CbNombreCuenta { get; set; }
        public string CbClabe { get; set; }
        public string CbConvenio { get; set; }
        public string CbBeneficiario { get; set; }
        public int CbEmpresa { get; set; }
        public bool? CbPagoManual { get; set; }
        public bool? CbPagoReferenciado { get; set; }
        public bool? CbPagoLinea { get; set; }
        public long CbUsuid { get; set; }
        public DateTime? CbFechaRegistro { get; set; }

        public virtual Bancos CbBanco { get; set; }
        public virtual Empresas CbEmpresaNavigation { get; set; }
        public virtual ActivoPara ActivoPara { get; set; }
    }
}