// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class DetalleConvenio
    {
        public int DcId { get; set; }
        public int DcConvenio { get; set; }
        public int DcCuentaDetalle { get; set; }
        public long DcUsuid { get; set; }
        public DateTime DcFechaRegistro { get; set; }

        public virtual Convenios DcConvenioNavigation { get; set; }
        public virtual DetalleCuentaPorCobrar DcCuentaDetalleNavigation { get; set; }
    }
}