// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class DetallePago
    {
        public int DpId { get; set; }
        public int DpPagoId { get; set; }
        public int DpCuentaDetalle { get; set; }
        public string DpDocLinea { get; set; }
        public decimal DpImporteAplicado { get; set; }
        public decimal DpImportePendiente { get; set; }
        public bool? DpSaldoCreado { get; set; }
        public long DpUsuid { get; set; }
        public DateTime DpFechaRegistro { get; set; }

        public virtual DetalleCuentaPorCobrar DpCuentaDetalleNavigation { get; set; }
        public virtual AlumnoPagos DpPago { get; set; }
    }
}