// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class Edificios
    {
        public Edificios()
        {
            Salones = new HashSet<Salones>();
        }

        public int EEdificioId { get; set; }
        public string ENombre { get; set; }
        public string EDescripcion { get; set; }

        public virtual ICollection<Salones> Salones { get; set; }
    }
}