// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class Escuelasf
    {
        public string EscuelasId { get; set; }
        public string EscuelasNombre { get; set; }
        public string EscuelasEstado { get; set; }
    }
}