// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class EsquemaPagoHistorial
    {
        public long EphAlumnoId { get; set; }
        public int EphFormasPagoId { get; set; }
        public DateTime EphFechaInicio { get; set; }
        public DateTime? EphFechaFin { get; set; }
        public float? FphMensualidadAnterior { get; set; }
        public string EphAutorizadoPor { get; set; }

        public virtual Alumno EphAlumno { get; set; }
        public virtual Administrativos EphAutorizadoPorNavigation { get; set; }
    }
}