// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class EstatusList
    {
        public EstatusList()
        {
            Alumno = new HashSet<Alumno>();
        }

        public int SlStatusId { get; set; }
        public int SlModuloId { get; set; }
        public string SlModulo { get; set; }
        public string SlNombre { get; set; }
        public string SlDescripcion { get; set; }

        public virtual ICollection<Alumno> Alumno { get; set; }
    }
}