// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class Facultades
    {
        public Facultades()
        {
            Carreras = new HashSet<Carreras>();
        }

        public decimal FacFacultadId { get; set; }
        public string FacNombre { get; set; }
        public string FacDescripcion { get; set; }

        public virtual ICollection<Carreras> Carreras { get; set; }
    }
}