// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class FaltasClase
    {
        public int FcMateriaId { get; set; }
        public long FcAlumnoId { get; set; }
        public DateTime FcFechaFalta { get; set; }
        public int FcFaltaId { get; set; }

        public virtual Alumno FcAlumno { get; set; }
        public virtual Materias FcMateria { get; set; }
    }
}