// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class FormaPago
    {
        public FormaPago()
        {
            AlumnoPagos = new HashSet<AlumnoPagos>();
            FormaPagoTxt = new HashSet<FormaPagoTxt>();
        }

        public int FpId { get; set; }
        public string FpClave { get; set; }
        public string FpDescripcion { get; set; }
        public bool? FpActivaManual { get; set; }
        public long FpUsuid { get; set; }
        public DateTime FpFechaRegistro { get; set; }

        public virtual ICollection<AlumnoPagos> AlumnoPagos { get; set; }
        public virtual ICollection<FormaPagoTxt> FormaPagoTxt { get; set; }
    }
}