// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class FormaPagoTxt
    {
        public int FptId { get; set; }
        public int FptFormaPago { get; set; }
        public string FptDescripcionTxt { get; set; }
        public long FptUsuid { get; set; }
        public DateTime FptFechaRegistro { get; set; }

        public virtual FormaPago FptFormaPagoNavigation { get; set; }
    }
}