// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class Horarios
    {
        public int HHorarioId { get; set; }
        public int HHoraInicio { get; set; }
        public int HMinutoInicio { get; set; }
        public int HHoraFin { get; set; }
        public int HMinutoFin { get; set; }
    }
}