// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class MediosContacto
    {
        public double? MdId { get; set; }
        public string MdNombre { get; set; }
        public string MdDescripcion { get; set; }
    }
}