// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class MetodoPago
    {
        public MetodoPago()
        {
            AlumnoPagos = new HashSet<AlumnoPagos>();
        }

        public int MpMetodoId { get; set; }
        public string MpClave { get; set; }
        public string MpDescripcion { get; set; }

        public virtual ICollection<AlumnoPagos> AlumnoPagos { get; set; }
    }
}