// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class Modalidades
    {
        public Modalidades()
        {
            Alumno = new HashSet<Alumno>();
            Carreras = new HashSet<Carreras>();
        }

        public int ModModalidadId { get; set; }
        public string ModNombre { get; set; }
        public string ModDescripcion { get; set; }

        public virtual ICollection<Alumno> Alumno { get; set; }
        public virtual ICollection<Carreras> Carreras { get; set; }
    }
}