// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class Momento
    {
        public int MMomentoId { get; set; }
        public string MNombre { get; set; }
        public string MDescripcion { get; set; }
    }
}