// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class Nacionalidades
    {
        public int NacionalidadesId { get; set; }
        public string NacionalidadesNombre { get; set; }
    }
}