// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class PermisosAlumnos
    {
        public int PaPermisoId { get; set; }
        public string PaNombre { get; set; }
        public string PaDescripcion { get; set; }
    }
}