// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class Permisos
    {
        public int PPermisoId { get; set; }
        public string PNombre { get; set; }
        public string PDescripcion { get; set; }
    }
}