// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class RegistroChecador
    {
        public int RcId { get; set; }
        public long RcAdminNumeroEmpleado { get; set; }
        public DateTime RcFechaRegistro { get; set; }
        public TimeSpan RcHoraRegistro { get; set; }
    }
}