// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class Salones
    {
        public int SSalonId { get; set; }
        public string SNombre { get; set; }
        public int SEdificio { get; set; }
        public string SDescripcion { get; set; }

        public virtual Edificios SEdificioNavigation { get; set; }
    }
}