// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class StatusPago
    {
        public StatusPago()
        {
            AlumnoPo = new HashSet<AlumnoPo>();
        }

        public int SpStatusId { get; set; }
        public string SpNombre { get; set; }
        public string SpDescripcion { get; set; }

        public virtual ICollection<AlumnoPo> AlumnoPo { get; set; }
    }
}