// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class StatusHistorial
    {
        public long ShAlumnoId { get; set; }
        public int ShStatus { get; set; }
        public DateTime ShFechaInicio { get; set; }
        public DateTime? ShFechaFin { get; set; }
        public string ShAutorizadoPor { get; set; }

        public virtual Alumno ShAlumno { get; set; }
        public virtual Administrativos ShAutorizadoPorNavigation { get; set; }
    }
}