// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class TiposJustificante
    {
        public int TjTipoId { get; set; }
        public string TjNombre { get; set; }
        public string TjDescripcion { get; set; }
    }
}