// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class TiposDocumentos
    {
        public int DocId { get; set; }
        public string DocNombre { get; set; }
        public string DocDescripcion { get; set; }
        public bool DocObligatorio { get; set; }
        public int? DocTipoPers { get; set; }
        public int? ModuloId { get; set; }

        public virtual TipoPersonas DocTipoPersNavigation { get; set; }
        public virtual Modulo Modulo { get; set; }
    }
}