// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class TipoPersonas
    {
        public TipoPersonas()
        {
            TiposDocumentos = new HashSet<TiposDocumentos>();
        }

        public int TpId { get; set; }
        public string TpNombre { get; set; }
        public string TpDescripcion { get; set; }

        public virtual ICollection<TiposDocumentos> TiposDocumentos { get; set; }
    }
}