// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class TipoBajaAlumno
    {
        public int TbaBajaId { get; set; }
        public string TbaNombre { get; set; }
        public string TbaDescripcion { get; set; }
    }
}