// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class TipoSeguimiento
    {
        public int TsId { get; set; }
        public string TsNombre { get; set; }
        public string TsDescripcion { get; set; }
    }
}