// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class TipoPagoAdmin
    {
        public int TpaId { get; set; }
        public string TpaNombre { get; set; }
        public string TpaDescripcion { get; set; }
    }
}