// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Data.Sql
{
    public partial class UsosFacturacion
    {
        public UsosFacturacion()
        {
            DatosFacturacion = new HashSet<DatosFacturacion>();
        }

        public string UfUsoId { get; set; }
        public decimal UfUso { get; set; }
        public string UfDescripcion { get; set; }

        public virtual ICollection<DatosFacturacion> DatosFacturacion { get; set; }
    }
}